#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=infra/gcp/scripts/lib.sh
source "${SCRIPT_DIR}/lib.sh"

require_cmd gcloud
require_cmd heroku
require_cmd jq
require_cmd rg
require_cmd curl

ENVIRONMENT="$(resolve_environment "${ENVIRONMENT:-production}")"
SECRET_PREFIX="${SECRET_PREFIX:-$(default_secret_prefix "${ENVIRONMENT}")}"

if [[ "${ENVIRONMENT}" == "production" ]]; then
  default_app_url="https://listygifty.com"
else
  default_app_url="https://staging.listygifty.com"
fi

PROJECT_ID="${PROJECT_ID:-listygifty}"
HEROKU_APP="${HEROKU_APP:-$(resolve_heroku_app "${ENVIRONMENT}")}"
BINDINGS_OUTPUT="${BINDINGS_OUTPUT:-${ROOT_DIR}/.gcp/heroku-secret-bindings-${ENVIRONMENT}.env}"
SYNC_EMPTY_VALUES="${SYNC_EMPTY_VALUES:-0}"
INCLUDE_DATABASE_URL_BINDING="${INCLUDE_DATABASE_URL_BINDING:-0}"
CLERK_DISCOVERY_URL="${CLERK_DISCOVERY_URL:-${NEXT_PUBLIC_APP_URL:-${default_app_url}}}"
SECRET_CLERK_PUBLISHABLE_KEY="${SECRET_CLERK_PUBLISHABLE_KEY:-${SECRET_PREFIX}clerk-publishable-key}"

if [[ -z "${HEROKU_APP}" ]]; then
  echo "HEROKU_APP must be set (for example: export HEROKU_APP=your-heroku-app). You can also set HEROKU_APP_PRODUCTION or HEROKU_APP_STAGING." >&2
  exit 1
fi

mkdir -p "$(dirname "${BINDINGS_OUTPUT}")"

log "Loading Heroku config from ${HEROKU_APP} (ENVIRONMENT=${ENVIRONMENT})"
HEROKU_CONFIG_JSON="$(heroku config --json -a "${HEROKU_APP}")"

read_config_var() {
  local key="$1"
  printf '%s' "${HEROKU_CONFIG_JSON}" | jq -r --arg KEY "$key" '.[$KEY] // empty'
}

append_binding() {
  local env_name="$1"
  local secret_name="$2"

  if [[ "${BOUND_KEYS}" == *",${env_name},"* ]]; then
    return
  fi

  printf '%s=%s\n' "${env_name}" "${secret_name}" >>"${BINDINGS_OUTPUT}"
  BOUND_KEYS="${BOUND_KEYS}${env_name},"
}

{
  echo "# Generated by infra/gcp/scripts/sync-heroku-secrets.sh"
  echo "# ENVIRONMENT=${ENVIRONMENT}"
  echo "# HEROKU_APP=${HEROKU_APP}"
  echo "# Format: ENV_VAR=SECRET_NAME"
} >"${BINDINGS_OUTPUT}"
BOUND_KEYS=","

while IFS= read -r env_name; do
  value="$(read_config_var "${env_name}")"

  if [[ -z "${value}" && "${SYNC_EMPTY_VALUES}" != "1" ]]; then
    warn "Heroku variable ${env_name} is empty; skipping"
    continue
  fi

  target_env_name="${env_name}"
  target_secret_key="${env_name}"

  # Keep the original Heroku DB URL for reference without replacing Cloud SQL DATABASE_URL.
  if [[ "${env_name}" == "DATABASE_URL" ]]; then
    target_env_name="HEROKU_DATABASE_URL"
    target_secret_key="HEROKU_DATABASE_URL"
  fi

  secret_name="$(env_var_to_secret_name "${target_secret_key}" "${SECRET_PREFIX}")"
  upsert_secret "${PROJECT_ID}" "${secret_name}" "${value}"
  log "Synced ${env_name} -> secret/${secret_name}"

  if [[ "${env_name}" == "DATABASE_URL" && "${INCLUDE_DATABASE_URL_BINDING}" != "1" ]]; then
    warn "Skipping runtime binding for DATABASE_URL (saved as HEROKU_DATABASE_URL)."
    continue
  fi

  append_binding "${target_env_name}" "${secret_name}"
done < <(printf '%s' "${HEROKU_CONFIG_JSON}" | jq -r 'keys[]' | sort)

publishable_key="$(read_config_var "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY")"
if [[ -z "${publishable_key}" && -n "${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:-}" ]]; then
  publishable_key="${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}"
fi
if [[ -z "${publishable_key}" ]]; then
  publishable_key="$(curl -fsSL "${CLERK_DISCOVERY_URL}" | rg -o 'pk_(test|live)_[A-Za-z0-9]+' | head -n 1 || true)"
fi

if [[ -n "${publishable_key}" ]]; then
  upsert_secret "${PROJECT_ID}" "${SECRET_CLERK_PUBLISHABLE_KEY}" "${publishable_key}"
  append_binding "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" "${SECRET_CLERK_PUBLISHABLE_KEY}"
  log "Synced Clerk publishable key -> secret/${SECRET_CLERK_PUBLISHABLE_KEY}"
else
  warn "Could not detect Clerk publishable key. Set NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY and rerun."
fi

log "Heroku env var sync complete"
log "Secret binding file generated: ${BINDINGS_OUTPUT}"
